### Site info:
title: Matt's Thoughts On NLP Papers
author: Matt Gardner
email: mg1@cs.cmu.edu
description: "Thoughts on NLP papers."
baseurl: /paper-thoughts

### Personal info and site tools info:
github_username:  matt-gardner
favicon:     "/images/favicon.ico"
aboutme_photo: https://i.imgur.com/15BT1.jpg # your photo.

### Site setting:
ShowContactInfo: "True"
default_column: "two"

### Build settings
highlighter: pygments
paginate: 5
markdown: redcarpet
kramdown:
  input: GFM  # this was to fix a parsing error, I think with code blocks
